### ISSUE TITLE
Demo page is not accessible

### ISSUE THREAD

**Issue by AlexPasternak** [kayvanbree/f10k#35]
The demo URL referenced in ReadMe.md is not accessible and shows 404 error.
https://kayvanbree.github.io/f10k/tracks

If the demo is not available yet, that should be mentioned in the ReadMe for now.
<img width="598" alt="2019-08-20 9 10 37 AM" src="https://user-images.githubusercontent.com/1819485/63349920-6b6f2680-c32a-11e9-9f37-6b4e7cebbad3.png">

**Comment by kayvanbree** [comment]
Hey @AlexPasternak,

Thanks for your issue!

This is because I'm hosting the static files on GitHub pages. If you go to https://kayvanbree.github.io/f10k it will go to index.html, which is correct, but when you go to https://kayvanbree.github.io/f10k/tracks it will look up /tracks/index.html. That file does not exist. The solution for now is to only use that first link, and let Angular do its routing magic. 

I created issue #29 for this.

If everything is correct, the application should now also automatically do the authorization whenever the token is expired, but I will still need to create a backend to implement an Authorization flow that supports refresh tokens.

[edit] I also quickly turned off playlist import as it is still broken.

**Comment by kayvanbree** [comment]
Closing in favor of #29
